name: Update README with Projects and Contributions

on:
  schedule:
    - cron: '0 0 * * 1' # Runs once a week at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Repositories and Contributions
        run: |
          echo "## Projects and Contributions" > README.md

          # Fetch all repositories including private
          repos=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos?per_page=100)

          for repo in $(echo "$repos" | jq -r '.[].full_name'); do
            # Count commits for each repository
            commit_count=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$repo/commits?per_page=1 | jq -r '. | length')
            echo "- [${repo}](https://github.com/${repo}): $commit_count commits" >> README.md
          done

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with private project contributions"
          git push
